
version: 2

sources:
  - name: 'TPCH_SF1000'
    tables:
      - name: Part
      - name: Partsupp
      - name: Supplier
      - name: Nation
      - name: Region
      

  - name: dbt_snowflake_sample
    database: snowflake_sample_data
  